name: Update AKS Operator in rancher/charts
on:
  workflow_dispatch:
    inputs:
      charts_ref:
        description: "Submit PR against the following rancher/charts branch (e.g. dev-v2.7)"
        required: true
        default: "dev-v2.8"
      prev_aks_operator:
        description: "Previous AKS operator version (e.g. 1.1.0-rc2)"
        required: true
        default: ""
      new_aks_operator:
        description: "New AKS operator version"
        required: true
        default: ""
      prev_chart:
        description: "Previous Rancher Chart version (e.g. 101.1.0)"
        required: true
        default: ""
      new_chart:
        description: "New Rancher Chart version"
        required: true
        default: ""
      should_replace:
        description: "Should the old AKS operator version be replaced/removed? (e.g. true in case of release candidate bumps)"
        required: true
        default: "true"
jobs:
  update-rancher-chart:
    uses: mjura/highlander-reusable-workflows/.github/workflows/update-rancher-charts.yaml@main
    with:
      charts_ref: ${{ github.event.inputs.charts_ref }}
      operator: aks-operator
      prev_operator_version: ${{ github.event.inputs.prev_aks_operator }}
      new_operator_version: ${{ github.event.inputs.new_aks_operator }}
      prev_chart_version: ${{ github.event.inputs.prev_chart }}
      new_chart_version: ${{ github.event.inputs.new_chart }}
      should_replace: ${{ github.event.inputs.should_replace }}
    secrets:
      token: ${{secrets.CI_BOT_TOKEN}}
